apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: techtrends-prod
  namespace: argocd
spec:
  destination:
    namespace: sandbox
    server: https://kubernetes.default.svc
  project: sandbox
  source:
    helm:
      valueFiles:
      - values-prod.yaml
    path: project/helm/
    repoURL: https://github.com/lmortizt/nd064_course_1
